server:
  port: "8008"

database:
  host: "db.golang.host"
  port: 5432
  username: "admin_go"
  password: "admin_go"
  dbname: "user"

redis:
  host: "redis.golang.host"
  port: 6379
  password: "admin_go"